[package]
name = "antwerp"
version = "0.1.0"
edition = "2021"
description = "static website generator"

[profile.dev]
opt-level = 1

[dependencies]
colored = "2.0.0"
glob = "0.3.0"
grass = "0.11.0"
regex = "1.6.0"
serde = { version = "1.0.139", features = ["derive"] }
tera = "1.16.0"
titlecase = "2.0.0"
